#!/bin/sh

# Find everything inside folder fcst_phy2m125 of -type f (files)
# and then pipe ( | )  the output into awk
# awk splits the input using field splitter '/' ( -F"/") and with the result it prints 
# print "cdo -f nc copy "$0" ./output/"$3".nc" where ${0} is the full input line (e.g. ./fcst_phy2m125/file123)
# and $3 is the third is file123 in the previous example.
# the output (print) generated by awk for each file found is finally piped into another shell to execute 
# ( the last | sh ) part of the line

find ./fcst_phy2m125 -type f | awk -F"/" '{ print "cdo -f nc copy "$0" ./output/"$3".nc" }' | sh
